### ISSUE TITLE
New improved sqrti function

### ISSUE THREAD

**Issue by juliencombattelli** [reivax-boucoi/AVR#6]
Here is an improved version of sqrti. As the actual one, it returns the round up integer square root. It is 121 asm instructions long vs 137 for the actual version. Also, it does NOT have this bug with negative binary shift ;)

```C++
uint16_t sqrti2(uint32_t x)
{
    if(x<2) return x;
    uint16_t res=0;
    uint16_t add= 0x8000;
    int i;
    for(i=0;i<16;i++)
    {
        uint16_t temp=res | add;
        uint32_t g2=(temp-1)*(temp-1);
        if (x>g2)
        {
            res=temp;
        }
        add>>=1;
    }
    return res;
}
```
I have tried to optimized ```temp-1``` which appear twice, but I did not succeed ...

**Comment by reivax-boucoi** [comment]
I appears to return the rounded down integer root, but this is still better than what I had before. Thanks !
